"""empty message

Revision ID: 1a8cb299571
Revises: None
Create Date: 2015-12-04 05:55:28.323470

"""

# revision identifiers, used by Alembic.
revision = '1a8cb299571'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gitlab_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('refresh_token', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gitlab_account_email'), 'gitlab_account', ['email'], unique=False)
    op.create_index(op.f('ix_gitlab_account_username'), 'gitlab_account', ['username'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wechat_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('with_contact_privilege', sa.Boolean(), nullable=True),
    sa.Column('uid', sa.Unicode(length=32), nullable=False),
    sa.Column('agentid', sa.Integer(), nullable=False),
    sa.Column('secret', sa.Unicode(), nullable=False),
    sa.Column('token', sa.Unicode(), nullable=False),
    sa.Column('aeskey', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_wechat_app_uid'), 'wechat_app', ['uid'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('wx_user_id', sa.Unicode(length=255), nullable=False),
    sa.Column('password', sa.Unicode(length=255), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('avatar', sa.Unicode(length=1024), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('comment', sa.UnicodeText(), nullable=True),
    sa.Column('gitlab_account_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.Unicode(length=255), nullable=True),
    sa.Column('current_login_ip', sa.Unicode(length=255), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gitlab_account_id'], ['gitlab_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_wx_user_id'), 'user', ['wx_user_id'], unique=True)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_user_wx_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_wechat_app_uid'), table_name='wechat_app')
    op.drop_table('wechat_app')
    op.drop_table('role')
    op.drop_index(op.f('ix_gitlab_account_username'), table_name='gitlab_account')
    op.drop_index(op.f('ix_gitlab_account_email'), table_name='gitlab_account')
    op.drop_table('gitlab_account')
    ### end Alembic commands ###
